// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvoaauvzleuihozzkecf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2b2FhdXZ6bGV1aWhvenprZWNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MTUyMjcsImV4cCI6MjA2MDk5MTIyN30.kEXJBpDXBKXXA0q01mh-YUsGh4UnL7fHKdrtnvplU30";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);